# -*- coding: utf-8 -*-
"""apriori.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Rfxdjav_QLmBiOYSRo57dOK0GRpL4_qF
"""

import pandas as pd

data=pd.read_csv('/content/Groceries data.csv')

data.head()

d1=data.groupby('Member_number')['itemDescription'].apply(list).to_list()

d1[3]

from mlxtend.preprocessing import TransactionEncoder

pre=TransactionEncoder()

res1=pre.fit_transform(d1)

d2=pd.DataFrame(res1,columns=pre.columns_)

d2.head()

d2.replace(False,0,inplace=True)

d2.replace(True,1,inplace=True)

d2.head()

from mlxtend.frequent_patterns import apriori,association_rules

support=apriori(d2,min_support=.1,use_colnames=True)

support.sort_values(by='support',ascending=False).head()

confidence=association_rules(support,metric='confidence',min_threshold=.5)

confidence.sort_values(by='confidence',ascending=False).head()

